/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED
/*
 * Core Applications
 */
#define CONFIG_USER_INIT_INIT 1
#define CONFIG_USER_INIT_CONSOLE_SH 1
#undef  CONFIG_USER_INIT_RUN_FIREWALL
#define CONFIG_USER_SASH_SH 1
#undef  CONFIG_USER_SH_SH
#undef  CONFIG_USER_NWSH_SH
#undef  CONFIG_USER_BASH_BASH
#undef  CONFIG_USER_OTHER_SH
#undef  CONFIG_USER_SASH_HISTORY
#define CONFIG_USER_SASH_REBOOT 1
#undef  CONFIG_USER_SASH_SHUTDOWN
#define CONFIG_USER_INIT_EXPAND 1
#undef  CONFIG_USER_INIT_EXPAND_NOZEROES
#undef  CONFIG_USER_VERSION_VERSION
#undef  CONFIG_USER_LOGIN_LOGIN
#undef  CONFIG_USER_OLD_PASSWORDS
#undef  CONFIG_USER_ONLY_ROOT
#undef  CONFIG_USER_AGETTY_AGETTY
#undef  CONFIG_USER_GETTYD_GETTYD
#undef  CONFIG_USER_LOGIN_PASSWD
#undef  CONFIG_USER_CRON_CRON
/*
 * Real Time Clock
 */
#undef  CONFIG_USER_HWCLOCK_HWCLOCK
#undef  CONFIG_USER_RTC_M41T11
#undef  CONFIG_USER_RTC_DS1302
/*
 * Vixie-cron
 */
#undef  CONFIG_USER_VIXIECRON_CRON
#undef  CONFIG_USER_VIXIECRON_CRONTAB
/*
 * at
 */
#undef  CONFIG_USER_AT_AT
#undef  CONFIG_USER_AT_ATD
#undef  CONFIG_USER_AT_ATRUN
/*
 * Library Configuration
 */
/*
 * Force build (Normally built when required)
 */
#undef  CONFIG_LIB_LIBAES_FORCE
#undef  CONFIG_LIB_LIBDES_FORCE
#undef  CONFIG_LIB_LIBSSL_FORCE
#undef  CONFIG_LIB_LIBGMP_FORCE
#undef  CONFIG_LIB_LIBG_FORCE
#undef  CONFIG_LIB_LIBLDAP_FORCE
#undef  CONFIG_LIB_LIBPAM_FORCE
#undef  CONFIG_LIB_LIBPCAP_FORCE
#undef  CONFIG_LIB_ZLIB_FORCE
#undef  CONFIG_LIB_LIBATM_FORCE
#undef  CONFIG_LIB_LIBPNG_FORCE
#undef  CONFIG_LIB_LIBJPEG_FORCE
#undef  CONFIG_LIB_NCURSES_FORCE
/*
 * Library Configuration
 */
#undef  CONFIG_LIB_UC_LIBC_TIMEZONE
/*
 * Flash Tools
 */
#undef  CONFIG_USER_FLASHW_FLASHW
#undef  CONFIG_USER_NETFLASH_NETFLASH
#undef  CONFIG_USER_RECOVER_STATIC_TFTP
#undef  CONFIG_USER_RECOVER_RECOVER
#undef  CONFIG_USER_BOOTTOOLS_FLASHLOADER
#undef  CONFIG_USER_BOOTTOOLS_HIMEMLOADER
/*
 * MTD utils
 */
#undef  CONFIG_USER_MTDUTILS
/*
 * Filesystem Applications
 */
#undef  CONFIG_USER_FLATFSD_FLATFSD
#define CONFIG_USER_MOUNT_MOUNT 1
#define CONFIG_USER_MOUNT_UMOUNT 1
#undef  CONFIG_USER_FDISK_FDISK
#undef  CONFIG_USER_FDISK_SFDISK
/*
 * EXT2
 */
#undef  CONFIG_USER_E2FSPROGS_E2FSCK_E2FSCK
#undef  CONFIG_USER_E2FSPROGS_MISC_MKE2FS
#undef  CONFIG_USER_E2FSPROGS_MISC_BADBLOCKS
#undef  CONFIG_USER_E2FSPROGS_MISC_CHATTR
#undef  CONFIG_USER_E2FSPROGS_MISC_DUMPE2FS
#undef  CONFIG_USER_E2FSPROGS_MISC_E2LABEL
#undef  CONFIG_USER_E2FSPROGS_MISC_FSCK
#undef  CONFIG_USER_E2FSPROGS_MISC_LSATTR
#undef  CONFIG_USER_E2FSPROGS_MISC_MKLOST_FOUND
#undef  CONFIG_USER_E2FSPROGS_MISC_TUNE2FS
#undef  CONFIG_USER_E2FSPROGS_MISC_UUIDGEN
/*
 * RESIERFS
 */
#undef  CONFIG_USER_REISERFSPROGS
#undef  CONFIG_USER_REISERFSPROGS_DEBUGRESIERFS
#undef  CONFIG_USER_REISERFSPROGS_MKREISERFS
#undef  CONFIG_USER_REISERFSPROGS_REISERFSCK
#undef  CONFIG_USER_REISERFSPROGS_RESIZE_REISERFS
#undef  CONFIG_USER_REISERFSPROGS_UNPACK
/*
 * SAMBA
 */
#undef  CONFIG_USER_SAMBA
#undef  CONFIG_USER_SAMBA_SMBD
#undef  CONFIG_USER_SAMBA_NMBD
#undef  CONFIG_USER_SAMBA_SMBMOUNT
#undef  CONFIG_USER_SAMBA_SMBUMOUNT
/*
 * SMBFS
 */
#undef  CONFIG_USER_SMBMOUNT_SMBMOUNT
#undef  CONFIG_USER_SMBMOUNT_SMBUMOUNT
/*
 * CRAMFS
 */
#undef  CONFIG_USER_CRAMFS_CRAMFSCK
#undef  CONFIG_USER_CRAMFS_MKCRAMFS
/*
 * Network Applications
 */
#undef  CONFIG_USER_ROUTE_ARP
#undef  CONFIG_USER_FNORD_HTTPD
#undef  CONFIG_USER_BOA_SRC_BOA
#undef  CONFIG_USER_BPALOGIN_BPALOGIN
#undef  CONFIG_USER_BR2684CTL_BR2684CTL
#undef  CONFIG_USER_BRCFG_BRCFG
#undef  CONFIG_USER_BRCTL_BRCTL
#undef  CONFIG_USER_DHCPCD_DHCPCD
#undef  CONFIG_USER_DHCPCD_NEW_DHCPCD
#undef  CONFIG_USER_DHCPD_DHCPD
#undef  CONFIG_USER_DHCP_ISC_SERVER_DHCPD
#undef  CONFIG_USER_DHCP_ISC_CLIENT_DHCLIENT
#undef  CONFIG_USER_DHCP_ISC_RELAY_DHCRELAY
#undef  CONFIG_USER_DIALD_DIALD
#undef  CONFIG_USER_DISCARD_DISCARD
#undef  CONFIG_USER_DNSMASQ_DNSMASQ
#undef  CONFIG_USER_ETHATTACH_ETHATTACH
#undef  CONFIG_USER_EZIPUPDATE_EZIPUPDATE
#undef  CONFIG_USER_FTP_FTP_FTP
#undef  CONFIG_USER_FTPD_FTPD
#undef  CONFIG_USER_FREESWAN
#undef  CONFIG_USER_HTTPD_HTTPD
#undef  CONFIG_USER_IFATTACH_IFATTACH
#undef  CONFIG_USER_ROUTE_IFCONFIG
#undef  CONFIG_USER_INETD_INETD
#undef  CONFIG_USER_IPCHAINS_IPCHAINS
#undef  CONFIG_USER_IPFWADM_IPFWADM
#undef  CONFIG_USER_IPMASQADM_IPMASQADM
#undef  CONFIG_USER_IPPORTFW_IPPORTFW
#undef  CONFIG_USER_IPREDIR_IPREDIR
#undef  CONFIG_USER_IPROUTE2
#undef  CONFIG_USER_IPTABLES_IPTABLES
#undef  CONFIG_USER_KENDIN_CONFIG
#undef  CONFIG_USER_KLAXON_KLAXON
#undef  CONFIG_USER_L2TPD_L2TPD
#undef  CONFIG_USER_LOATTACH_LOATTACH
#undef  CONFIG_USER_SMTP_SMTPCLIENT
#undef  CONFIG_USER_MAIL_MAIL_IP
#undef  CONFIG_USER_MINI_HTTPD_MINI_HTTPD
#undef  CONFIG_USER_MSNTP_MSNTP
#undef  CONFIG_USER_NESSUS_NASL
#undef  CONFIG_USER_ROUTE_NETSTAT
#undef  CONFIG_USER_NETSTAT_NAT_NETSTAT_NAT
#undef  CONFIG_USER_ROUTE_MIITOOL
#undef  CONFIG_USER_NTPD_NTPD
#undef  CONFIG_USER_NTPD_NTPDATE
#undef  CONFIG_USER_NTPD_NTPQ
#undef  CONFIG_USER_OPENSSL_APPS
#undef  CONFIG_USER_PING_PING
#undef  CONFIG_USER_PLUG_PLUG
#undef  CONFIG_USER_PORTMAP_PORTMAP
#undef  CONFIG_USER_PPPD_PPPD_PPPD
#undef  CONFIG_USER_PPTPD_PPTPCTRL
#undef  CONFIG_USER_PPTPD_PPTPD
#undef  CONFIG_USER_PPTP_CLIENT_PPTP
#undef  CONFIG_USER_PPTP_CLIENT_PPTP_CALLMGR
#undef  CONFIG_USER_RDATE_RDATE
#undef  CONFIG_USER_ROUTE_ROUTE
#undef  CONFIG_USER_ROUTED_ROUTED
#undef  CONFIG_USER_RP_PPPOE_PPPOE
#undef  CONFIG_USER_SETHDLC_SETHDLC
#undef  CONFIG_USER_SLATTACH_SLATTACH
#undef  CONFIG_USER_SNMPD_SNMPD
#undef  CONFIG_USER_STUNNEL_STUNNEL
#undef  CONFIG_USER_SSLWRAP_SSLWRAP
#undef  CONFIG_USER_SQUID_SQUID
#undef  CONFIG_USER_SSH_SSH
#undef  CONFIG_USER_SSH_SSHD
#undef  CONFIG_USER_SSH_SSHKEYGEN
#undef  CONFIG_USER_STP_STP
#undef  CONFIG_USER_TCPWRAP_TCPD
#undef  CONFIG_USER_TCPBLAST_TCPBLAST
#undef  CONFIG_USER_TCPDUMP_TCPDUMP
#undef  CONFIG_USER_TELNETD_TELNETD
#undef  CONFIG_USER_TELNET_TELNET
#undef  CONFIG_USER_TFTP_TFTP
#undef  CONFIG_USER_TFTPD_TFTPD
#undef  CONFIG_USER_THTTPD_THTTPD
#undef  CONFIG_USER_TRACEROUTE_TRACEROUTE
#undef  CONFIG_USER_UCDSNMP_SNMPD
#undef  CONFIG_USER_VCONFIG_VCONFIG
#undef  CONFIG_USER_VPNLED_VPNLED
#undef  CONFIG_USER_WGET
#undef  CONFIG_USER_ZEBRA_ZEBRA_ZEBRA
/*
 * Net-tools
 */
#undef  CONFIG_USER_NET_TOOLS_ARP
#undef  CONFIG_USER_NET_TOOLS_HOSTNAME
#undef  CONFIG_USER_NET_TOOLS_IFCONFIG
#undef  CONFIG_USER_NET_TOOLS_NAMEIF
#undef  CONFIG_USER_NET_TOOLS_NETSTAT
#undef  CONFIG_USER_NET_TOOLS_PLIPCONFIG
#undef  CONFIG_USER_NET_TOOLS_RARP
#undef  CONFIG_USER_NET_TOOLS_ROUTE
#undef  CONFIG_USER_NET_TOOLS_SLATTACH
#undef  CONFIG_USER_NET_TOOLS_MII_TOOL
/*
 * Wireless-tools
 */
#undef  CONFIG_USER_WIRELESS_TOOLS
#undef  CONFIG_USER_HOSTAP_HOSTAP
#undef  CONFIG_USER_WLAN_NG
/*
 * Miscellaneous Applications
 */
#undef  CONFIG_USER_LANG_A60
#undef  CONFIG_USER_CAL_CAL
#undef  CONFIG_USER_CHAT_CHAT
#undef  CONFIG_USER_CKSUM_CKSUM
#undef  CONFIG_USER_CLOCK_CLOCK
#undef  CONFIG_USER_CPU_CPU
#undef  CONFIG_USER_CAL_DATE
#undef  CONFIG_USER_DHRYSTONE_DHRYSTONE
#undef  CONFIG_USER_DE2TSCAL_DE2TSCAL
#undef  CONFIG_USER_FROB_LED_FROB_LED
#undef  CONFIG_USER_GDBSERVER_GDBREPLAY
#undef  CONFIG_USER_GDBSERVER_GDBSERVER
#undef  CONFIG_USER_HD_HD
#undef  CONFIG_USER_LCD_LCD
#undef  CONFIG_USER_LEDBLINK
#undef  CONFIG_USER_LEDCON_LEDCON
#undef  CONFIG_USER_LILO_LILO
#undef  CONFIG_USER_LISSA_LISSA
#undef  CONFIG_USER_USBCBI_USBCBI
#undef  CONFIG_USER_USBISO_USBISO
#undef  CONFIG_USER_MATH_TEST
#undef  CONFIG_USER_MAWK_AWK
#undef  CONFIG_USER_MYSQL
#undef  CONFIG_USER_NULL_NULL
#undef  CONFIG_USER_PALMBOT_PALMBOT
#undef  CONFIG_USER_PCMCIA_CS
#undef  CONFIG_USER_PERL_PERL
#undef  CONFIG_USER_PYTHON_PYTHON
#undef  CONFIG_USER_READPROFILE_READPROFILE
#undef  CONFIG_USER_ROOTLOADER_ROOTLOADER
#undef  CONFIG_USER_SETSERIAL_SETSERIAL
#undef  CONFIG_USER_TRIPWIRE_SIGGEN
#undef  CONFIG_USER_STRACE_STRACE
#undef  CONFIG_USER_STTY_STTY
#undef  CONFIG_USER_TCSH_TCSH
#undef  CONFIG_USER_TINYTCL_TCLSH
#undef  CONFIG_USER_THREADDEMOS_THREADDEMOS
#undef  CONFIG_USER_TIP_TIP
#undef  CONFIG_USER_TRIPWIRE_TRIPWIRE
#undef  CONFIG_USER_LRZSZ_LRZSZ
/*
 * LIRC
 */
#undef  CONFIG_USER_LIRC
/*
 * Editors
 */
#define CONFIG_USER_LEVEE_VI 1
#undef  CONFIG_USER_ELVISTINY_VI
/*
 * Audio tools
 */
#undef  CONFIG_USER_MP3PLAY_MP3PLAY
#undef  CONFIG_USER_OGGPLAY_OGG123
#undef  CONFIG_USER_OGGPLAY_EXAMPLE
#undef  CONFIG_USER_MUSICBOX_MUSICBOX
#undef  CONFIG_USER_PLAY_PLAY
#undef  CONFIG_USER_PLAY_TONE
#undef  CONFIG_USER_VPLAY_VPLAY
#undef  CONFIG_USER_VPLAY_VREC
#undef  CONFIG_USER_VPLAY_MIXER
#undef  CONFIG_USER_PLAYRT_PLAYRT
/*
 * Video tools
 */
#undef  CONFIG_USER_W3CAM_VIDCAT
#undef  CONFIG_USER_W3CAM_W3CAMD
/*
 * Fileutils tools
 */
#undef  CONFIG_USER_FILEUTILS_CAT
#undef  CONFIG_USER_FILEUTILS_CHGRP
#undef  CONFIG_USER_FILEUTILS_CHMOD
#undef  CONFIG_USER_FILEUTILS_CHOWN
#undef  CONFIG_USER_FILEUTILS_CMP
#undef  CONFIG_USER_FILEUTILS_CP
#undef  CONFIG_USER_FILEUTILS_DD
#undef  CONFIG_USER_FILEUTILS_GREP
#undef  CONFIG_USER_FILEUTILS_L
#undef  CONFIG_USER_FILEUTILS_LN
#undef  CONFIG_USER_FILEUTILS_LS
#undef  CONFIG_USER_FILEUTILS_MKDIR
#undef  CONFIG_USER_FILEUTILS_MKFIFO
#undef  CONFIG_USER_FILEUTILS_MKNOD
#undef  CONFIG_USER_FILEUTILS_MORE
#undef  CONFIG_USER_FILEUTILS_MV
#undef  CONFIG_USER_FILEUTILS_RM
#undef  CONFIG_USER_FILEUTILS_RMDIR
#undef  CONFIG_USER_FILEUTILS_SYNC
#undef  CONFIG_USER_FILEUTILS_TOUCH
/*
 * Shutils tools
 */
#undef  CONFIG_USER_SHUTILS_BASENAME
#undef  CONFIG_USER_SHUTILS_DATE
#undef  CONFIG_USER_SHUTILS_DIRNAME
#undef  CONFIG_USER_SHUTILS_ECHO
#undef  CONFIG_USER_SHUTILS_FALSE
#undef  CONFIG_USER_SHUTILS_LOGNAME
#undef  CONFIG_USER_SHUTILS_PRINTENV
#undef  CONFIG_USER_SHUTILS_PWD
#undef  CONFIG_USER_SHUTILS_TRUE
#undef  CONFIG_USER_SHUTILS_UNAME
#undef  CONFIG_USER_SHUTILS_WHICH
#undef  CONFIG_USER_SHUTILS_WHOAMI
#undef  CONFIG_USER_SHUTILS_YES
/*
 * Sysutils tools
 */
#undef  CONFIG_USER_SYSUTILS_REBOOT
#undef  CONFIG_USER_SYSUTILS_SHUTDOWN
#undef  CONFIG_USER_SYSUTILS_DF
#undef  CONFIG_USER_SYSUTILS_FREE
#undef  CONFIG_USER_SYSUTILS_HOSTNAME
#undef  CONFIG_USER_SYSUTILS_KILL
#undef  CONFIG_USER_SYSUTILS_PS
/*
 * Procps tools
 */
#undef  CONFIG_USER_PROCPS_FREE
#undef  CONFIG_USER_PROCPS_KILL
#undef  CONFIG_USER_PROCPS_PGREP
#undef  CONFIG_USER_PROCPS_PKILL
#undef  CONFIG_USER_PROCPS_PS
#undef  CONFIG_USER_PROCPS_SNICE
#undef  CONFIG_USER_PROCPS_SYSCTL
#undef  CONFIG_USER_PROCPS_TLOAD
#undef  CONFIG_USER_PROCPS_TOP
#undef  CONFIG_USER_PROCPS_UPTIME
#undef  CONFIG_USER_PROCPS_VMSTAT
#undef  CONFIG_USER_PROCPS_W
#undef  CONFIG_USER_PROCPS_WATCH
/*
 * PCI utilities
 */
#undef  CONFIG_USER_PCIUTILS_LSPCI
#undef  CONFIG_USER_PCIUTILS_SETPCI
/*
 * BusyBox
 */
#undef  CONFIG_USER_BUSYBOX_BUSYBOX
/*
 * Tinylogin
 */
#undef  CONFIG_USER_TINYLOGIN_TINYLOGIN
/*
 * MicroWindows
 */
#undef  CONFIG_USER_MICROWIN
/*
 * Games
 */
#undef  CONFIG_USER_GAMES_ADVENT4
#undef  CONFIG_USER_GAMES_DUNGEON
#undef  CONFIG_USER_GAMES_RUBIK
/*
 * Miscellaneous Configuration
 */
#undef  CONFIG_USER_RAMIMAGE_NONE
#undef  CONFIG_USER_RAMIMAGE_RAMFS64
#undef  CONFIG_USER_RAMIMAGE_RAMFS128
#define CONFIG_USER_RAMIMAGE_RAMFS256 1
#undef  CONFIG_USER_RAMIMAGE_RAMFS512
#undef  CONFIG_USER_RAMIMAGE_RAMFS1024
#undef  CONFIG_USER_RAMIMAGE_RAMFS2048
#undef  CONFIG_USER_RAMIMAGE_RAMFS8192
#undef  CONFIG_USER_CGI_GENERIC
#undef  CONFIG_USER_CGIHTML
#undef  CONFIG_USER_DEMO_BUTTON
#undef  CONFIG_USER_DEMO_LATCH
#undef  CONFIG_USER_DEMO_MORSE
#undef  CONFIG_USER_DEMO_R2100
/*
 * Debug Builds
 */
#undef  CONFIG_LIB_DEBUG
#undef  CONFIG_USER_DEBUG
/*
 * Debug tools
 */
#undef  CONFIG_USER_TIMEPEG_TPT
/*
 * Debug libraries
 */
#undef  CONFIG_LIB_LIBCCMALLOC
#define CONFIG_VENDOR "Apple"
#define CONFIG_PRODUCT "MacPlus"
#define CONFIG_LINUXDIR "linux-2.0.x"
#define CONFIG_LIBCDIR "libc"
#define CONFIG_LANGUAGE ""
#define VENDORS_AUTOCONF_INCLUDED
#undef AUTOCONF_INCLUDED
